### ISSUE TITLE
Module not found: Error: Can't resolve 'date-fns'

### ISSUE THREAD

**Issue by mohammad-quanit** [IOMechs/angular-year-calendar#2]
After installing this package, when I, include their configuration in App.module and run the app, I am getting this error:

> ERROR in ./node_modules/@iomechs/angular-year-calendar/fesm2015/iomechs-angular-year-calendar.js
Module not found: Error: Can't resolve 'date-fns' in '/home/mquanit/Documents/Projects/Angular Typescript Practice/shiny-ivy-app/node_modules/@iomechs/angular-year-calendar/fesm2015'

before that, i am also getting this error:

> ERROR in node_modules/@iomechs/angular-year-calendar/lib/components/year-calendar/year-calendar.component.d.ts:4:34 - error TS2307: Cannot find module '@angular/cdk/overlay'.
4 import { CdkOverlayOrigin } from '@angular/cdk/overlay';
ERROR in @iomechs/angular-year-calendar/iomechs-angular-year-calendar.ts(18,5): Error during template compile of 'YearCalendarModule'
  Could not resolve @angular/cdk/overlay relative to [object Object]..
There is no directive with "exportAs" set to "cdkOverlayOrigin" ("_body__month__inner__week__day {{ycConfig?.dayClass}}"
              cdkOverlayOrigin
              [ERROR ->]#heatMapEventDayTrigger="cdkOverlayOrigin"
              (click)="eventDayCick(day, heatMapEventDayTr")

but I solved it by doing `yarn add @angular/cdk/overlay`, but now I am getting the above issue, which is related to date-fns i guess.

**Comment by Mohammad-Quanit** [comment]
Here's the package.json file:

> {
  "name": "shiny-ivy-app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.2.11",
    "@angular/cdk": "^8.2.3",
    "@angular/common": "~8.2.11",
    "@angular/compiler": "~8.2.11",
    "@angular/core": "~8.2.11",
    "@angular/forms": "~8.2.11",
    "@angular/platform-browser": "~8.2.11",
    "@angular/platform-browser-dynamic": "~8.2.11",
    "@angular/router": "~8.2.11",
    "@iomechs/angular-year-calendar": "^0.1.1",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.12",
    "@angular/cli": "~8.3.12",
    "@angular/compiler-cli": "~8.2.11",
    "@angular/language-service": "~8.2.11",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  }
}

**Comment by mohammad-quanit** [comment]
Solved, that issue by doing 

> yarn add date-fns -S

but i am wondering, why i have to install both these libs manually?

**Comment by mohammad-quanit** [comment]
Is it any sample provided for heat map color directive. I am struggling to set on for `myCalendarConfig` property for ycConfig

**Comment by AhsanAyaz** [comment]
@Mohammad-Quanit thanks for reporting the issue 👍 
I'm looking into fixing the date-fns issue. I know why it's happening. Should be fixed with the next release.
Regarding the heat map color directive, can you please open a new issue with details to what you've tried and what seems to be the issue?
Thanks!

**Comment by AhsanAyaz** [comment]
@Mohammad-Quanit , I've added the dependencies to `peerDependencies`. If you install the latest release [0.1.5](https://github.com/IOMechs/angular-year-calendar/releases/tag/0.1.5). you'll see warnings about those if they're not installed.
